package laboratorio.pkg4;
import java.awt.BorderLayout;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static laboratorio.pkg4.SubjectParameters.TableStudents;
import static laboratorio.pkg4.SubjectParameters.Check;
import static laboratorio.pkg4.SubjectParameters.NumberNotes;
import static laboratorio.pkg4.SubjectParameters.NumberStudents;
import org.jfree.chart.ChartPanel;



/**
 *
 * @author User
 */
public final class Interface extends javax.swing.JFrame {
    
    Subject Students = new Subject();
    int Counter = 0;
    FileManagement ExportFile = new FileManagement();
    Graphic GenerateGraphic = new Graphic();

    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
        if(Check){
            Students.Students = TableStudents;
            ArrayList Aux = (ArrayList) Students.Students.get(0);
            int Columns = Aux.size();
            int Rows = Students.Students.size();
            ScoresTable.setModel(new DefaultTableModel(Rows, Columns));
            FinalTable.setModel(new DefaultTableModel(Rows, 4));
            Students.ScoreAverage();
            SetToTable(Rows,Columns);
            AddStudent.setEnabled(false);
        }
        else{
            
            ScoresTable.setModel(new DefaultTableModel(NumberStudents, NumberNotes+2));
            ScoresTable.setEnabled(false);
            FinalTable.setModel(new DefaultTableModel(NumberStudents, 4));
            FinalTable.setEnabled(false);
        
        }
    }
    public void SetToTable(int Rows, int Columns){
        
        NumStudents.setText(String.valueOf(Rows));
        NumNotes.setText(String.valueOf(Columns-2));
        for(int i=0; i<Rows; i++){
            ArrayList Row1 = (ArrayList) Students.Students.get(i);
            ArrayList Row2 = (ArrayList) Students.StudentAverage.get(i);
            for(int j=0; j<Columns; j++)
                ScoresTable.setValueAt(Row1.get(j), i, j);
            for(int a=0; a<4; a++)
                FinalTable.setValueAt(Row2.get(a), i, a);
            }
        ScoresTable.setEnabled(false);
        FinalTable.setEnabled(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jMenu1 = new javax.swing.JMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        ScoresTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        NumStudents = new javax.swing.JLabel();
        NumNotes = new javax.swing.JLabel();
        AddStudent = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        FinalTable = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        CodeStudent = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        Nuevo = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1000, 520));
        setMinimumSize(new java.awt.Dimension(1000, 520));
        setPreferredSize(new java.awt.Dimension(1000, 520));
        getContentPane().setLayout(null);

        ScoresTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(ScoresTable);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 80, 380, 170);

        jLabel1.setText("Cantidad de estudiantes:");
        jLabel1.setPreferredSize(new java.awt.Dimension(130, 20));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(15, 15, 130, 20);

        jLabel2.setText("Notas por estudiante:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(15, 40, 130, 20);
        getContentPane().add(NumStudents);
        NumStudents.setBounds(150, 15, 50, 20);
        getContentPane().add(NumNotes);
        NumNotes.setBounds(150, 40, 50, 20);

        AddStudent.setText("Agregar Estudiante");
        AddStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddStudentActionPerformed(evt);
            }
        });
        getContentPane().add(AddStudent);
        AddStudent.setBounds(205, 40, 170, 25);

        FinalTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(FinalTable);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(20, 270, 380, 180);

        jLabel5.setText("Código del estudiante:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(450, 20, 140, 20);
        getContentPane().add(CodeStudent);
        CodeStudent.setBounds(590, 20, 100, 25);

        jButton2.setText("Mostrar Grafico");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(720, 20, 130, 25);

        jMenu2.setText("Archivo");

        jMenu4.setText("Guardar");

        jMenuItem4.setText("Tabla Principal");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem4);

        jMenuItem5.setText("Tabla Promedios");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem5);

        jMenu2.add(jMenu4);

        Nuevo.setText("Nuevo");
        Nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoActionPerformed(evt);
            }
        });
        jMenu2.add(Nuevo);

        jMenuItem3.setText("Cerrar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        try {
            ExportFile.ExportFile(Students.Students);
        } catch (IOException ex) {
            Logger.getLogger(Interface.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        try {
            ExportFile.ExportFile(Students.StudentAverage);
        } catch (IOException ex) {
            Logger.getLogger(Interface.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void AddStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddStudentActionPerformed
        if(Counter==NumberStudents)
            JOptionPane.showMessageDialog(this,"Ya ha completado el total de estudiantes");
        else{
            String Name=JOptionPane.showInputDialog("Ingrese el nombre del estudiante :" );
            String Document=JOptionPane.showInputDialog("Ingrese documento :");
            String[] Notes = new String[NumberNotes];       
            for (int i = 0;i<NumberNotes;i++) 
                Notes[i] = JOptionPane.showInputDialog("Ingrese la nota "+(i+1)+" :");
            if((Name!=null) && (Document!=null) && (Notes!=null)){
                Students.EnterStudent(Name, Document, Notes);
                ArrayList Columns = (ArrayList) Students.Students.get(0);
                SetToTable(Students.Students.size(), Columns.size());
                Counter++;
            }
        }

    }//GEN-LAST:event_AddStudentActionPerformed

    private void NuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoActionPerformed
        if(JOptionPane.showConfirmDialog(this, "¿Desea guardar el archivo actual?")==0){
            String[] Options = {"Tabla Principal","Tabla Promedios", "Amabas tablas"};
            int Value = JOptionPane.showOptionDialog(this, "¿Qué tabla desea guardar?", "Guardar", WIDTH, HEIGHT, null,
                    Options, Options[0]);
            switch (Value) {
                case 0:
                    try {
                        ExportFile.ExportFile(Students.Students);
                    } catch (IOException ex) {
                        Logger.getLogger(Interface.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    break;
                case 1:
                    try {
                        ExportFile.ExportFile(Students.StudentAverage);
                    } catch (IOException ex) {
                        Logger.getLogger(Interface.class.getName()).log(Level.SEVERE, null, ex);
                    }   break;
                case 2:
                    try {
                        ExportFile.ExportFile(Students.Students);
                        ExportFile.ExportFile(Students.StudentAverage);
                    } catch (IOException ex) {
                        Logger.getLogger(Interface.class.getName()).log(Level.SEVERE, null, ex);
                    }   break;
                default:
                    break;
            }
        }
        SubjectParameters OpenInterface = new SubjectParameters();
        OpenInterface.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_NuevoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int position = 0, n =0;
        for(int i=0; i<Students.Students.size(); i++){
            ArrayList Aux =  (ArrayList) Students.Students.get(i);
            position = Aux.indexOf(CodeStudent);
            n=i;
        }
        ArrayList List = (ArrayList)Students.Students.get(n);
        ChartPanel chartPanel=new ChartPanel(GenerateGraphic.MakeGraphic(List));
        
        add(chartPanel);
        chartPanel.setBounds(450, 50, 400, 400);
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddStudent;
    private javax.swing.JTextField CodeStudent;
    private javax.swing.JTable FinalTable;
    private javax.swing.JMenuItem Nuevo;
    private javax.swing.JLabel NumNotes;
    private javax.swing.JLabel NumStudents;
    private javax.swing.JTable ScoresTable;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
